export {ProductCard} from './ProductCard/ProductCard';
export {Header} from '../pages/Header/Header';
export {About} from '../pages/About/About';
export {Cart} from '../pages/Cart/Cart';
export {Catalog} from '../pages/Catalog/Catalog';
export {Contact} from '../pages/Contact/Contact';
export {RegisterForm} from '../pages/Profile/RegisterForm';
export {LoginForm} from '../pages/Profile/LoginForm';
export {Footer} from './Footer/Footer';
